### ISSUE TITLE
Crash on feature toggle fetch in native image

### ISSUE THREAD

**Issue by janfreymann** [quarkiverse/quarkus-unleash#179]
Hi,

the integration of the quarkus-unleash extension is fine in a JVM-based context, but once we deployed the application as a native image with Graalvm, the following crash happened on startup:

```
java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: java.util.ServiceConfigurationError: java.net.ContentHandlerFactory: Provider sun.awt.www.content.MultimediaContentHandlers not found
	at java.base@17.0.8/java.util.ServiceLoader.fail(ServiceLoader.java:593)
	at java.base@17.0.8/java.util.ServiceLoader.loadProvider(ServiceLoader.java:875)
	at java.base@17.0.8/java.util.ServiceLoader$ModuleServicesLookupIterator.hasNext(ServiceLoader.java:1084)
	at java.base@17.0.8/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base@17.0.8/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at java.base@17.0.8/java.net.URLConnection$2.run(URLConnection.java:1401)
	at java.base@17.0.8/java.net.URLConnection$2.run(URLConnection.java:1391)
	at java.base@17.0.8/java.security.AccessController.executePrivileged(AccessController.java:171)
	at java.base@17.0.8/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.base@17.0.8/java.net.URLConnection.lookupContentHandlerViaProvider(URLConnection.java:1390)
	at java.base@17.0.8/java.net.URLConnection.getContentHandler(URLConnection.java:1303)
	at java.base@17.0.8/java.net.URLConnection.getContent(URLConnection.java:760)
	at java.base@17.0.8/sun.net.www.protocol.https.HttpsURLConnectionImpl.getContent(HttpsURLConnectionImpl.java:404)
	at io.getunleash.repository.HttpFeatureFetcher.getFeatureResponse(HttpFeatureFetcher.java:60)
	at io.getunleash.repository.HttpFeatureFetcher.fetchFeatures(HttpFeatureFetcher.java:38)
	at io.getunleash.repository.FeatureRepository.lambda$updateFeatures$0(FeatureRepository.java:96)
	at io.getunleash.repository.FeatureRepository.initCollections(FeatureRepository.java:80)
	at io.getunleash.repository.FeatureRepository.<init>(FeatureRepository.java:40)
	at io.getunleash.repository.FeatureRepository.<init>(FeatureRepository.java:28)
	at io.getunleash.DefaultUnleash.defaultToggleRepository(DefaultUnleash.java:50)
	at io.getunleash.DefaultUnleash.<init>(DefaultUnleash.java:54)
	at io.quarkiverse.unleash.runtime.UnleashCreator.createUnleash(UnleashCreator.java:31)
	at io.quarkiverse.unleash.runtime.UnleashService.initialize(UnleashService.java:30)
	at io.quarkiverse.unleash.runtime.UnleashService_ClientProxy.initialize(Unknown Source)
	at io.quarkiverse.unleash.runtime.UnleashRecorder.initializeProducers(UnleashRecorder.java:12)
	at io.quarkus.deployment.steps.UnleashProcessor$configureRuntimeProperties116716570.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.UnleashProcessor$configureRuntimeProperties116716570.deploy(Unknown Source)
	... 7 more
```

Version info:
* Quarkus version `3.2.4.Final`
* base image: `mandrel:23.0.1.2.83-Final-java17-amd64`
* `io.quarkiverse.unleash:quarkus-unleash:1.0.1`
* `io.getunleash:unleash-client-java:8.0.0`

Is this something which should be addressed in the reflection config? 

Thanks for your help :)

**Comment by andrejpetras** [comment]
HI @janfreymann, thank you for reporting this issue. This has been fixed in the latest version, “1.1.0”.
